import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Nike Slim Shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '/images/p1.png',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'High quality shirt',
  },
  {
    name: 'Adidas Fit Shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '/images/p2.avif',
    price: 100,
    countInStock: 15,
    brand: 'Adidas',
    rating: 4.2,
    numReviews: 8,
    description: 'Comfortable and stylish fit shirt',
  },
  {
    name: 'Puma Slim Pants',
    slug: 'puma-slim-pants',
    category: 'Pants',
    image: '/images/p3.avif',
    price: 80,
    countInStock: 20,
    brand: 'Puma',
    rating: 4.3,
    numReviews: 12,
    description: 'High-quality slim pants for daily wear',
  },
  {
    name: 'Under Armour Joggers',
    slug: 'under-armour-joggers',
    category: 'Pants',
    image: '/images/p4.avif',
    price: 90,
    countInStock: 18,
    brand: 'Under Armour',
    rating: 4.6,
    numReviews: 15,
    description: 'Durable and comfortable joggers',
  },
]
